### ISSUE TITLE
Bad link to Datastax Object Mapper documentation

### ISSUE THREAD

**Issue by cgruver** [datastax/cassandra-quarkus#177] opened 2021-05-27 23:00 UTC
The link in the quick start guide to: https://docs.datastax.com/en/developer/java-driver/latest/manual/mapper results in a 404.

Links may be version specific now: https://docs.datastax.com/en/developer/java-driver/4.11/manual/mapper/

**Comment by adutra** [comment] 2021-06-01 09:43
Hi @cgruver thanks for reporting this! In fact, links to "latest" are perfectly fine, but there is a problem with our website right now and these links are not being redirected to the specific version as they should be. We are working on a fix, hang tight!

**Comment by adutra** [comment] 2021-06-21 13:44
The problem is fixed now. Thanks!

**Closed by adutra** 2021-06-21 13:44 UTC
