### ISSUE TITLE
Enforce api/internal package conventions

### ISSUE THREAD

**Issue by olim7t** [datastax/cassandra-quarkus#62] opened 2020-06-04 16:47 UTC
Some of the package in the `runtime` module follow the [driver API conventions](https://docs.datastax.com/en/developer/java-driver/4.6/manual/api_conventions/):
```
com.datastax.oss.quarkus.runtime.api
com.datastax.oss.quarkus.runtime.internal
```
But that has not been applied consistently:
* package `config` is directly under `quarkus`
* packages `graal`, `health` and `metrics` are directly under `runtime`.
* classes `AbstractCassandraClientProducer` and `CassandraClientRecorder` are directly under `runtime`.

Move types to their correct location, depending on what's an "official" API for application developers, vs what's an internal implementation detail. I think most should go to internal, except maybe the config classes and the health check, depending on how they're supposed to be used (?)

The `deployment` module is used at build time only, so it doesn't matter that much. But following what we did for `mapper-processor` I would suggest putting everything into `internal`.

`quickstart` and `integration-tests` don't matter.

**Comment by adutra** [comment] 2020-06-04 19:11
@olim7t there was already #27 open for that. However I think we first need to assess whether or not it makes sense to use the api/internal distinction for this project. We don't have formalized contribution guidelines yet, so that's open for debate. We also have #34 to add a CONTRIBUTING file.

**Comment by tomekl007** [comment] 2020-06-08 10:11
closed because this is a duplicate of: https://github.com/datastax/cassandra-quarkus/issues/27

**Closed** 2020-06-08 10:11 UTC
